"""
This is a setup.py script generated by py2applet

For future development. 

See https://py2app.readthedocs.io/en/latest/tutorial.html#create-a-setup-py-file

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['simple_rigol_grab.py']
DATA_FILES = []
OPTIONS = {}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
